version: "3"

services:
  rabbitmq1:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: /usr/local/bin/entrypoint.sh

  rabbitmq2:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq2
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: /usr/local/bin/entrypoint.sh

  rabbitmq3:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq3
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: /usr/local/bin/entrypoint.sh

  haproxy:
    image: haproxy:1.7
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
